### ISSUE TITLE
Other tags?

### ISSUE THREAD

**Issue by steveostudios** [taggon/gulp-plist#1]
Is there any way to do anything other than add/edit a string? Say, an array or dict?

**Comment by taggon** [comment]
@steveostudios 
Just pass them via json. You can add/edit a `Date`, `String`, `Number` `Array` and even a plain `Object` that turns into a dict.
I think `test.js` is a good example.

**Comment by steveostudios** [comment]
Sweet! I should have checked there first! Thanks for a great tool!
